// Cover Ultra Premium — helper for jsPDF
// Usage:
//   await drawUltraPremiumCover(doc, {
//     lang: state?.lang || 'en',
//     title: i18n('cover.title'),
//     periodLabel: i18n('cover.period'),
//     periodValue: '2026-01-01 → 2026-03-01',
//     logoUrl: 'assets/brand/budgetwise_lockup_dark.png',
//     watermarkUrl: 'assets/brand/ff_watermark_white.png',
//   });
//
// Works frontend-only. Designed to be "drop-in" without breaking existing export code.

async function drawUltraPremiumCover(doc, opts = {}) {
  const {
    lang = 'en',
    title = 'Decision Report',
    periodLabel = 'Period',
    periodValue = '',
    footer = 'Generated by WiseScore™',
    logoUrl = 'assets/brand/budgetwise_lockup_dark.png',
    watermarkUrl = 'assets/brand/ff_watermark_white.png',
    brandName = 'BudgetWise',
    subtitle = 'Decision Intelligence Platform',
  } = opts;

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // === Background (executive dark blue) ===
  // Solid + subtle gradients (approx) using translucent overlays
  doc.setFillColor(6, 18, 42);
  doc.rect(0, 0, pageW, pageH, 'F');

  // Soft radial-ish glow (simulated with big translucent circles)
  doc.setFillColor(46, 123, 255);
  doc.setGState?.(new doc.GState({ opacity: 0.12 }));
  doc.circle(pageW * 0.62, pageH * 0.38, Math.max(pageW, pageH) * 0.45, 'F');
  doc.setGState?.(new doc.GState({ opacity: 0.06 }));
  doc.circle(pageW * 0.30, pageH * 0.20, Math.max(pageW, pageH) * 0.38, 'F');
  doc.setGState?.(new doc.GState({ opacity: 1 }));

  // === Watermark (FF monogram, white ~6% opacity) ===
  try {
    const wm = await fetchAsDataURL(watermarkUrl);
    // If GState supported, enforce 6% opacity; otherwise rely on image alpha.
    if (doc.setGState && doc.GState) doc.setGState(new doc.GState({ opacity: 0.06 }));
    const wmW = pageW * 0.72;
    const wmH = wmW; // square-ish
    doc.addImage(wm, 'PNG', (pageW - wmW) / 2, (pageH - wmH) / 2 + pageH * 0.04, wmW, wmH, undefined, 'FAST');
    if (doc.setGState && doc.GState) doc.setGState(new doc.GState({ opacity: 1 }));
  } catch (_) {
    // ignore watermark if unavailable
  }

  // === Logo (top center) ===
  let logoH = 0;
  try {
    const logo = await fetchAsDataURL(logoUrl);
    const logoW = pageW * 0.64;
    logoH = logoW * 0.28; // approximate lockup ratio
    doc.addImage(logo, 'PNG', (pageW - logoW) / 2, pageH * 0.10, logoW, logoH, undefined, 'FAST');
  } catch (_) {
    // fallback: text brand
    doc.setTextColor(242, 246, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.text(brandName, pageW / 2, pageH * 0.13, { align: 'center' });
  }

  // Subtitle (Decision Intelligence Platform)
  doc.setTextColor(242, 246, 255);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(subtitle.toUpperCase(), pageW / 2, pageH * 0.10 + (logoH || 0) + 18, { align: 'center' });

  // === Center title (multilingual, dynamic) ===
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(34);
  doc.setTextColor(242, 246, 255);
  doc.text(title, pageW / 2, pageH * 0.52, { align: 'center', maxWidth: pageW * 0.84 });

  // Period chip (optional)
  if (periodValue) {
    const chipY = pageH * 0.60;
    doc.setFillColor(0, 0, 0);
    if (doc.setGState && doc.GState) doc.setGState(new doc.GState({ opacity: 0.18 }));
    doc.roundedRect(pageW * 0.22, chipY - 14, pageW * 0.56, 28, 6, 6, 'F');
    if (doc.setGState && doc.GState) doc.setGState(new doc.GState({ opacity: 1 }));

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(242, 246, 255);
    doc.text(`${periodLabel.toUpperCase()}  ${periodValue}`, pageW / 2, chipY + 4, { align: 'center' });
  }

  // === Footer ===
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(242, 246, 255);
  if (doc.setGState && doc.GState) doc.setGState(new doc.GState({ opacity: 0.65 }));
  doc.text(footer.toUpperCase(), pageW / 2, pageH - 22, { align: 'center' });
  if (doc.setGState && doc.GState) doc.setGState(new doc.GState({ opacity: 1 }));
}

async function fetchAsDataURL(url) {
  const res = await fetch(url, { cache: 'force-cache' });
  if (!res.ok) throw new Error('Failed to load asset: ' + url);
  const blob = await res.blob();
  return await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
